---
version: "3"
services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: unless-stopped
    volumes:
      - /mnt/storage/download:/downloads
      - /mnt/storage/odroid/compose/jackett/conf:/config
    environment:
        TZ: Europe/Rome
        PUID: 1000
        PGID: 1000
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
        - 9117:9117
