---
version: "3"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    volumes:
      - /mnt/storage/tv:/tv
      - /mnt/storage/movies:/movies
      - /mnt/storage/odroid/compose/jellyfin/conf/config:/config
      - /mnt/storage/odroid/compose/jellyfin/conf/cache:/cache
    environment:
        TZ: Europe/Rome
        PUID: 1000
        PGID: 1000
        JELLYFIN_PublishedServerUrl: 192.168.1.13
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
        - 8096:8096
        - 8920:8920
        - 7359:7359/udp
        - 1900:1900/udp
