---
version: "3"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    volumes:
      - /mnt/storage/tv:/tv
      - /mnt/storage/download:/downloads
      - /mnt/storage/odroid/compose/sonarr/conf:/config
    environment:
        TZ: Europe/Rome
        PUID: 1000
        PGID: 1000
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
        - 8989:8989
