---
version: "3"
services:
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    restart: unless-stopped
    volumes:
        - /mnt/storage/download:/downloads
        - /mnt/storage/download/toWatch:/watch
        - /mnt/storage/odroid/compose/transmission/conf:/config
    environment:
        TZ: Europe/Rome
        PUID: 1000
        PGID: 1000
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
        - 9091:9091
        - 51413:51413
        - 51413:51413/udp
