---
version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/storage/odroid/compose/watchtower/conf:/config
    environment:
        TZ: Europe/Rome
        PUID: 1000
        PGID: 1000
        WATCHTOWER_CLEANUP: "true"
        WATCHTOWER_LABEL_ENABLE: "true"
        WATCHTOWER_INCLUDE_RESTARTING: "true"
        WATCHTOWER_POLL_INTERVAL: 7200
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
