---
version: "3"
services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    privileged: true
    volumes:
      - /mnt/storage/odroid/compose/caddy/conf/Caddyfile:/etc/caddy/Caddyfile
      - /mnt/storage/odroid/compose/caddy/conf/data:/data
      - /mnt/storage/odroid/compose/caddy/conf/config:/config
      - /mnt/storage/odroid/compose/caddy/conf/certs:/certs
    environment:
        TZ: Europe/Rome
        PUID: 1000
        PGID: 1000
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
        - 80:80
        - 443:443
