---
version: "3"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    volumes:
        - /mnt/storage/odroid/compose/qbittorrent/conf:/config
        - /mnt/storage/download:/downloads
    environment:
        TZ: Europe/Rome
        PUID: 1000
        PGID: 1000
        WEBUI_PORT: 9091
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
        - 9091:9091
        - 6881:6881
        - 6881:6881/udp
