---
version: "3"
services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: unless-stopped
    privileged: true
    volumes:
      - /mnt/storage/odroid/compose/adguardhome/conf/config:/opt/adguardhome/conf
      - /mnt/storage/odroid/compose/adguardhome/conf/work:/opt/adguardhome/work
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 5580:80/tcp
      - 443:443/tcp
      - 443:443/udp
      - 3000:3000/tcp
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
